### ISSUE TITLE
GFF truncated

### ISSUE THREAD

**Issue by Kekananen** [blachlylab/recontig#8]
GFF files appear to be truncated
original GFF:
```
#!genome-build GRCh38.p13
#!genome-version GRCh38
#!genome-date 2013-12
#!genome-build-accession GCA_000001405.28
#!genebuild-last-updated 2021-03
1	ensembl_havana	gene	685679	686673	.	-	.	gene_id "ENSG00000284662"; gene_version "1"; gene_name "OR4F16"; gene_source "ensembl_havana"; gene_biotype "protein_coding";
```
The converted GFF being now:
```
#!genome-build GRCh38.p13
#!genome-version GRCh38
#!genome-date 2013-12
#!genome-build-accession GCA_000001405.28
#!genebuild-last-updated 2021-03
# contig names remapped with recontig version 1.0.0. cmd: 
0284662"; gene_version "1"; gene_name "OR4F16"; gene_source "ensembl_havana"; gene_biotype "protein_coding";
1	ensembl_havana	transcript	685679	686673	.	-	.	gene_id "ENSG00000284662"; gene_version "1"; transcript_id "ENST00000332831"; transcript_version "4"; gene_name "OR4F16"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "OR4F16-201"; transcript_source "ensembl_havana"; transcript_biotype "protein_coding"; tag "CCDS"; ccds_id "CCDS41221"; tag "basic"; transcript_support_level "NA (assigned to previous version 3)";
```

**Comment by charlesgregory** [comment]
Was this with `pyrecontig.py` or the binary? As I am having no issues when doing this with the binary.

**Comment by Kekananen** [comment]
`pyrecontig.py ` was throwing this not the binary; however, it was straight up the wrapper and not any other functions messing with it. I haven't tried this since the most recent updates pull, however.

**Comment by jblachly** [comment]
1. if not resolved why is the issue closed?
2. the original file above looks truncated
3.  "The converted GFF being now:" looks like a typo, what does this mean?

**Comment by Kekananen** [comment]
1. This issue was resolved, through development though I'm not 100% sure when the issue was resolved. It no longer occurs, however in the working version. The issue this was described on was what I would have considered pre-release. 
2. Agreed.
3. "The original GFF being now:" would refer to the code snippet directly below it was not a typo but inferring the rest of the sentence from the snippet itself. I can see how that might be confusing, however.

Should have stated a reason for closing, will do in the future.

**Comment by jblachly** [comment]
Only thing I would say is it would be useful to figure out why it fixed itself because it could point to a corner case in your code that surfaces only rarely. Also a great reason to include extensive unit tests. Python and D have great support for this. Thomas can point you how to do CI. OK to close for now.
